# Generated by Django 6.1.1 on 2026-09-30 23:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveIntegerField(default=0)),
                ('score_a', models.PositiveIntegerField(blank=True, null=True)),
                ('score_b', models.PositiveIntegerField(blank=True, null=True)),
                ('pen_a', models.PositiveIntegerField(blank=True, null=True)),
                ('pen_b', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('awaiting', 'Aguardando confirmação'), ('confirmed', 'Confirmado'), ('disputed', 'Contestação aberta'), ('resolved', 'Resolvido pelo admin'), ('wo', 'WO')], default='pending', max_length=10)),
                ('extra_time', models.BooleanField(default=False, help_text='Foi à prorrogação')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('wo_reason', models.CharField(blank=True, max_length=200)),
                ('reports', models.JSONField(blank=True, default=dict)),
                ('proof_a', models.FileField(blank=True, null=True, upload_to='proofs/')),
                ('proof_b', models.FileField(blank=True, null=True, upload_to='proofs/')),
            ],
            options={
                'ordering': ['round__number', 'slot'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=10)),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=40)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('match_format', models.CharField(default='single', max_length=12)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('opened', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution', models.TextField(blank=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='core.match')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=250)),
                ('read', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('nickname', models.CharField(max_length=40)),
                ('ea_id', models.CharField(blank=True, max_length=60)),
                ('platform', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('avatar', models.URLField(blank=True)),
                ('avatar_file', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('team', models.CharField(blank=True, max_length=80)),
                ('campus', models.CharField(blank=True, max_length=120)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('seed', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('playoff', 'Playoff'), ('main', 'Fase principal'), ('eliminated', 'Eliminado'), ('blocked', 'Bloqueado'), ('champion', 'Campeão')], default='active', max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='negativo = punição, positivo = bônus')),
                ('reason', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='core.player')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='player_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.player'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=80)),
                ('jogo', models.CharField(blank=True, max_length=60)),
                ('tipo', models.CharField(blank=True, max_length=20)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('matricula', models.CharField(blank=True, max_length=30)),
                ('vinculo', models.CharField(blank=True, max_length=30)),
                ('phone_raw', models.CharField(blank=True, max_length=30)),
                ('phone_norm', models.CharField(db_index=True, max_length=15)),
                ('nick', models.CharField(blank=True, max_length=60)),
                ('equipe', models.CharField(blank=True, max_length=80)),
                ('nome_equipe', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('perfil', models.CharField(blank=True, max_length=40)),
                ('campus', models.CharField(blank=True, max_length=120)),
                ('curso', models.CharField(blank=True, max_length=120)),
                ('created_raw', models.CharField(blank=True, max_length=40)),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.player')),
            ],
            options={
                'ordering': ['-created_raw'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.round'),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('year', models.PositiveIntegerField()),
                ('config', models.JSONField(blank=True, default=dict)),
                ('champion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.player')),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='core.season'),
        ),
        migrations.AddField(
            model_name='player',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.season'),
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('score_a', models.PositiveIntegerField(blank=True, null=True)),
                ('score_b', models.PositiveIntegerField(blank=True, null=True)),
                ('pen_a', models.PositiveIntegerField(blank=True, null=True)),
                ('pen_b', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_time', models.BooleanField(default=False, help_text='Foi à prorrogação')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('awaiting', 'Aguardando confirmação'), ('confirmed', 'Confirmado'), ('disputed', 'Contestação aberta'), ('resolved', 'Resolvido pelo admin'), ('wo', 'WO')], default='pending', max_length=10)),
                ('wo_reason', models.CharField(blank=True, max_length=200)),
                ('reports', models.JSONField(blank=True, default=dict)),
                ('proof_a', models.FileField(blank=True, null=True, upload_to='proofs/')),
                ('proof_b', models.FileField(blank=True, null=True, upload_to='proofs/')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='core.match')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('match', 'number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('season', 'user')},
        ),
    ]
