# Generated by Django 5.2.17 on 2026-10-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="group",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="season",
            name="jogo",
            field=models.CharField(
                blank=True,
                help_text="Jogo/campeonato da planilha de inscrições que dá acesso a esta temporada (vazio = aceita qualquer inscrição)",
                max_length=60,
            ),
        ),
    ]
