# Generated by Django 5.2.17 on 2026-10-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_single_validation"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="checkin_open",
            field=models.BooleanField(
                default=True,
                help_text="Desligado = ninguém novo consegue fazer check-in (quem já fez continua entrando)",
            ),
        ),
    ]
